version: "3.9"

services:

  public:
    container_name: public-service
    build: 
      context: ./public
    ports:
      - 8080:3000
    networks:
      - public
      - private

  subscriptions:
    container_name: subscriptions-service
    build: 
      context: ./subscriptions
    ports:
      - 8081:3001
    networks:
      - private

  email:
    container_name: email-service
    build: 
      context: ./email
    ports:
      - 8082:3002
    networks:
      - private
      
  mongo:
    container_name: mongodb-service
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    networks:
      - private
    command: --quiet

networks:
    public:
    private:
        internal: true